# Generated by Django 6.1.1 on 2026-09-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizzamodel_created_at_pizzamodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pizzamodel',
            table='pizza',
        ),
    ]
