# Generated by Django 6.1.1 on 2026-10-04 11:15

import apps.user.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
    ]
