# Generated by Django 6.1.1 on 2026-10-05 14:54

import core.services.file_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_pizzamodel_name_alter_pizzamodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_pizza_photo),
        ),
    ]
