# Generated by Django 6.1.1 on 2026-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('cpu', models.CharField(max_length=100, verbose_name='Процесор')),
                ('ram_gb', models.IntegerField(verbose_name="Об'єм ОЗП (ГБ)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
            ],
        ),
    ]
